# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketAgent', '0002_auto_20161224_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='signup',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
